retail_dw:
  target: dev
  outputs:
    dev:
      type: postgres
      host:     "{{ env_var('DW_HOST', '') }}"
      port:     "{{ env_var('DW_PORT', '5432') | int }}"
      user:     "{{ env_var('DW_USER', '') }}"
      password: "{{ env_var('DW_PASSWORD', '') }}"
      dbname:   "{{ env_var('DW_DB', '') }}"
      schema:   silver        # default; overridden per model by dbt_project.yml
      threads:  4
      keepalives_idle: 0
      connect_timeout: 10